trigger:
- develop

resources:
- repo: self

pool:
  name: 'Self-Hosted-Pool'

variables:
  dockerRegistryServiceConnection: '1d20f035-29a3-4112-b566-110a1efd4a28'
  imageRepository: 'cloudyapi'
  containerRegistry: 'cloudycontainerregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'cloudycontainerregistry.azurecr.io'
        command: build
        dockerfile: '**/backend/Dockerfile'
        arguments: '-t Cloudy-api'
    - task: Docker@2
      inputs:
        containerRegistry: 'cloudycontainerregistry.azurecr.io'
        command: 'tag'
        arguments: 'Cloudy-api:latest cloudycontainerregistry.azurecr.io/Cloudy-api:latest'
        addPipelineData: false
        addBaseImageData: false
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'cloudycontainerregistry.azurecr.io'
        command: 'push'
        tags: 'cloudycontainerregistry.azurecr.io/Cloudy-api:latest'
        arguments: 'cloudycontainerregistry.azurecr.io/Cloudy-api:latest'
        addPipelineData: false
        addBaseImageData: false
- stage: Deploy
  displayName: Deploy to Azure Web
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure for Students(499e186f-6f01-4da4-aa17-f2fcbd575485)'
        appName: 'Cloudy-api'
        deployToSlotOrASE: true
        resourceGroupName: 'Cloudy'
        slotName: 'production'
        containers: 'cloudycontainerregistry.azurecr.io/Cloudy-api:latest'
        containerCommand: 'docker run --workdir=/app -p 443:3000'
        acrUsername: 'CloudyContainerRegistry'
        acrPassword: 'QwXips86bx1ZRzr/R3V6sNNLQ1tL5uKRsqKHnXAy80+ACRBDDqRs'