trigger:
- develop

resources:
- repo: self

pool:
  name: 'Self-Hosted-Pool'

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'CloudyContainerRegistry'
        repository: 'API'
        command: 'buildAndPush'
        Dockerfile: '**/backend/Dockerfile'
- stage: Deploy
  displayName: Deploy to Azure Web
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(499e186f-6f01-4da4-aa17-f2fcbd575485)'
        appType: 'webAppLinux'
        WebAppName: 'Cloudy-api'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'