trigger:
- develop

resources:
- repo: self

pool:
  name: 'Self-Hosted-Pool'

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: $(containerReg)
        repository: $(repository)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '-t cloudy-api'

    - task: Docker@2
      displayName: Tag the image
      inputs:
        containerRegistry: $(containerReg)
        repository: $(repository)
        command: 'tag'
        arguments: 'cloudy-api:latest  $(containerReg)/$(repository):latest'
        addPipelineData: false
        addBaseImageData: false

    - task: Docker@2
      displayName: Push the image
      inputs:
        containerRegistry: '$(containerReg)'
        repository: 'cloudy-api'
        command: 'push'
        tags: ':latest'
        

- stage: Deploy
  displayName: Deploy to Azure Web
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: '$(azureSub)'
        appName: 'Cloudy-api'
        deployToSlotOrASE: true
        resourceGroupName: 'Cloudy'
        slotName: 'production'
        containers: '$(containerReg)/$(repository):latest'
        containerCommand: 'docker run --workdir=/app -p 443:3000'
        acrUsername: '$(acrUser)'
